//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProject.DBConn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyProjectEntities : DbContext
    {
        public MyProjectEntities()
            : base("name=MyProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<DeptAdd> DeptAdds { get; set; }
        public virtual DbSet<DeptSal> DeptSals { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    
        public virtual ObjectResult<GetAlldeptData_Result> GetAlldeptData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlldeptData_Result>("GetAlldeptData");
        }
    }
}
